name: Trashcan
version: 1.1.0
author: Bytewave
main: horse.code.trashcan.Trashcan
api-version: 1.15
commands:
  trash:
    description: Opens the trashcan immediately
    usage: |
      /trash
    permission: trashcan.anywhere
    permission-message: To open the trashcan, you must right-click on an empty cauldron with an empty hand.
